 * Serving Flask app "rest" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://198.58.107.98:4242/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 924-138-081
173.8.111.114 - - [24/May/2019 12:49:07] "GET /blog/dragon HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/clients/blog-rest-api/rest.py", line 22, in get
    data = open(fileLoc, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'posts/dragon.md'
173.8.111.114 - - [24/May/2019 12:49:07] "GET /blog/dragon?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
173.8.111.114 - - [24/May/2019 12:49:07] "GET /blog/dragon?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
173.8.111.114 - - [24/May/2019 12:49:07] "GET /blog/dragon?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
173.8.111.114 - - [24/May/2019 12:49:08] "GET /blog/dragon?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
173.8.111.114 - - [24/May/2019 12:49:08] "GET /blog/dragon?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
173.8.111.114 - - [24/May/2019 12:49:09] "GET /blog/dragon?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
173.8.111.114 - - [24/May/2019 12:49:16] "GET /blog/first-post HTTP/1.1" 200 -
173.8.111.114 - - [24/May/2019 12:49:17] "GET /favicon.ico HTTP/1.1" 404 -
173.8.111.114 - - [24/May/2019 12:55:47] "GET /blog/first-post HTTP/1.1" 200 -
173.8.111.114 - - [24/May/2019 12:55:48] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '/home/clients/blog-rest-api/rest.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 924-138-081
